Adds primitives needed for BLS12-381 hash_to_curve for G2
keep-starknet-strange/garaga pull request #258
Opened 2024-11-28 16:20 UTC by petscheit

This PR adds map_to_curve, isogeny and cofactor clearing circuits for G2 points. This enables the conversion of hashes to G2 points

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

2024-11-28 16:22 UTC, petscheit commented on hydra/garaga/modulo_circuit.py
> +        # ToDo: the selection of which root to select is an unvalidated hint. Not sure if this can stay like this
Not sure if this is ok tbh. Probably its better to enforce his properly. Thoughts?

2024-12-10 14:09 UTC, feltroidprime requested changes

2024-12-10 14:09 UTC, feltroidprime commented on hydra/garaga/definitions.py
> +                889424345604814976315064405719089812568196182208668418962679585805340366775741747653930584250892369786198727235542,
Remove since it's already in signature.py

2024-12-10 14:09 UTC, feltroidprime commented on hydra/garaga/modulo_circuit.py
> +        return [self.mul(conj[0], norm_inv), self.mul(conj[1], norm_inv)]
This already exists and overwrite the function fp2_inv above.

2024-12-10 14:10 UTC, feltroidprime commented
Please apply suggestions and remove duplicate code.

2025-01-09 16:28 UTC, petscheit commented
@feltroidprime bump

2025-02-05 15:18 UTC, feltroidprime reviewed
Looks mergeable. Please apply final circuit modifications if you need.

2025-02-05 15:18 UTC, feltroidprime commented on hydra/garaga/precompiled_circuits/map_to_curve.py
Didn't reviewed it but lgtm.

2025-02-06 15:03 UTC, feltroidprime commented on hydra/garaga/precompiled_circuits/ec.py
> +        return y_coord, self.write_element(other_y, WriteOps.WITNESS)
Instead of writing two more elements and having s_bit as input, why not just returning y1 and y2 (and not include s_bit as input)

Then in cairo Zero you can find the correct root using s_bit and uint384_is_le

2025-02-06 15:05 UTC, petscheit commented on hydra/garaga/precompiled_circuits/ec.py
> +        return y_coord, self.write_element(other_y, WriteOps.WITNESS)
Sure, changing.

2025-02-06 15:15 UTC, feltroidprime commented on hydra/garaga/precompiled_circuits/ec.py
> +        return y_coord, self.write_element(other_y, WriteOps.WITNESS)
Suggestion was using fp_sqrt (which implictely does mul_and_assert) : 

![image](https://github.com/user-attachments/assets/a6d6833e-a3e7-4156-996d-99f9d034761d)

2025-02-06 15:23 UTC, petscheit commented on hydra/garaga/precompiled_circuits/ec.py
> +        return y_coord, self.write_element(other_y, WriteOps.WITNESS)
Ok this is much nicer.

2025-02-06 15:37 UTC, feltroidprime approved these changes

2025-02-06 15:39 UTC, merged